apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
  name: simon
  namespace: simon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: simon
subjects:
- kind: ServiceAccount
  name: simon
  namespace: simon
