---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-app-env
  labels:
    app: mysql-env
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: mysql-env
  template:
    metadata:
      labels:
        app: mysql-env
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        args:
          - "--ignore-db-dir=lost+found"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "changeme"
        - name: MYSQL_DATABASE
          value: "syseleven"
        - name: MYSQL_USER
          value: "syseleven"
        - name: MYSQL_PASSWORD
          value: "changeme"
        ports:
        - containerPort: 3306
          name: mysql-env
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-data
