---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  labels:
    app: mysql-env
spec:
  storageClassName: 
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
