---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    dns01:
      providers:
      - name: route53
        route53:
          accessKeyID: XXXXXXXX 
          region: eu-central-1
          secretAccessKeySecretRef:
            key: secret-access-key
            name: route53-credentials-secret
    email: admin@metakube.de 
    privateKeySecretRef:
      name: letsencrypt-acme-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
