apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  mysql-root-password: UGhvNXdlZVBoOVJhaDdhZQ==
  mysql-user: c3lzZWxldmVu
  mysql-database: c3lzZWxldmVu
  mysql-password: UmEyT3ppMW9ocjdqYWlRdTFFaQ==
