image:
  registry: docker.io
  repository: bitnami/external-dns
  tag: 0.5.16-debian-9-r8

## K8s resources type to be observed for new DNS entries by ExternalDNS
##
sources:
- service
- ingress

## DNS provider where the DNS records will be created. Available providers are:
## - aws, azure, cloudflare, coredns, designate, digitalocean, google, infoblox, rfc2136
##
provider: aws

aws:
  credentials:
    secretKey: "CHANGEME"
    accessKey: "CHANGEME"
    mountPath: "/.aws"
  region: "eu-central-1"

## Limit possible target zones by domain suffixes (optional)
##
domainFilters: []
##
## Adjust the interval for DNS updates
##
interval: "1m"
##
logLevel: info
##
## Modify how DNS records are sychronized between sources and providers (options: sync, upsert-only)
##
policy: upsert-only
##
## Registry Type. Available types are: txt, noop
##
registry: "txt"
##
## TXT Registry Identifier
##
txtOwnerId: "CHANGEME"

## Replica count
##
replicas: 1

## RBAC parameteres
## https://kubernetes.io/docs/reference/access-authn-authz/rbac/
##
rbac:
  create: true
  serviceAccountName: default

## Kubernetes Security Context
##
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]

podSecurityContext:
  fsGroup: 1001
  runAsUser: 1001
  runAsNonRoot: true

# Configure resource requests and limits
##
resources:
 limits:
   cpu: 50m
   memory: 50Mi
 requests:
   memory: 50Mi
   cpu: 10m

## Liveness Probe. The block is directly forwarded into the deployment, so you can use whatever livenessProbe configuration you want.
##
livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 2
  successThreshold: 1

## Readiness Probe. The block is directly forwarded into the deployment, so you can use whatever readinessProbe configuration you want.
##
readinessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

## Prometheus Exporter / Metrics
##
metrics:
  enabled: false
