apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # root password is required to be specified
  ROOT_PASSWORD: bE5vaGVjVGNKWkpEOXpONVdMSEM4bEpZanltdEhCZU1TUWtVeU1wbg==
  ## application credentials that will be created at cluster bootstrap
  DATABASE: c3lzZWxldmVu
  USER: bWV0YWt1YmU=
  PASSWORD: bE5vaGVjVGNKWkpEOWttc2xkbnN2c2Rhc2VF 
