---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webapp.<YOUR_NAME>.metakube.org
spec:
  rules:
  - host: webapp.<YOUR_NAME>.metakube.org
    http:
      paths:
      - path: /
        backend:
          serviceName: webapp-svc
          servicePort: http
